### ISSUE TITLE
Can you please share punctuator2tf2 pretrained model

### ISSUE THREAD

**Issue by pradeeplp** [cadia-lvl/punctuation-prediction#7]
Hi

Can you please share punctuator2tf2 pretrained model. I highly appreciate your work. Thanks

**Comment by helga-lvl** [comment]
Thanks! The links were only inside the pip-package but we have made a list in the README file now, so you should be able to access them. :)

**Comment by pradeeplp** [comment]
Thank you for this.

I ran play_with_model.py with the pretrained model and getting key error. Can you please point me in the right direction.

here is the stacktrace : 

Building model...
{0: '?QUESTIONMARK', 1: ',COMMA', 2: '.PERIOD', 3: '_SPACE'}

TEXT: good luck
good luck 
TEXT: how are you
how are you 
TEXT: hi how are you
hiTraceback (most recent call last):
  File "play_with_model.py", line 100, in <module>
    punctuate(word_vocabulary, punctuation_vocabulary, reverse_punctuation_vocabulary, text, net)
  File "play_with_model.py", line 49, in punctuate
    punctuation = reverse_punctuation_vocabulary[p_i]
**KeyError: 123**

**Comment by helga-lvl** [comment]
Note that the models are only trained in Icelandic. :) You can use the pip package provided for these models, use the models in Icelandic or train your own models in a language of your choice. 🙏

**Comment by pradeeplp** [comment]
Thank you ! appreciate your help.

**Comment by pradeeplp** [comment]
Can please point me in the right direction to save the model as .pb or .h5 and use them for inference. 

Any help is highly appreciated.

**Comment by helga-lvl** [comment]
We save them in the .pcl format. :)
